version: "3.9"

networks:
  network:
    external: true
    name: network

services:
  redis:
    container_name: redis
    image: redis:latest
    networks: 
      - network
  performance:
    image: performance:1.0
    ports:
      - "5000:8080"
    networks: 
      - network
    command: -l -p 8080 -r -rh redis
